Добавляет ссылку
htmlacademy-htmlcss/1946373-sedona-33 pull request #2
Opened 2022-01-19 07:38 UTC by Alissse

2022-01-23 15:00 UTC, Alissse commented
создает верстку

2022-01-24 21:08 UTC, baileys-li requested changes
Посмотри видео которые кидал в телегу. Потому что многие моменты повторяются

2022-01-24 21:08 UTC, baileys-li commented on catalog.html
> +                  <a class="button button-reset" type="reset" href="#">Сбросить</a>
не тот тэг
```suggestion
                  <button class="button button-apply" type="button" href="#">Применить</a>
                  <button  class="button button-reset" type="reset" href="#">Сбросить</a>
```

2022-01-24 21:08 UTC, baileys-li commented on catalog.html
> +                            <a class="product-card-button button" href="#">В избранное</a>
Избранному больше кнопка подходит (тип кнопка)

2022-01-24 21:08 UTC, baileys-li commented on catalog.html
> +      <footer></footer>
Редактор походу автозакрыл тэг. Поправь

2022-01-25 14:09 UTC, merged